### ISSUE TITLE
"Trying to add item, but missing meta box" error

### ISSUE THREAD

**Issue by gabriele-v** [gpac/gpac#2832]
Hello,
I need to extract some additional data (GoPro GPS data) from a MP4 file and add them to another MP4 file.
I'm able to extract them with the command
`mp4box.exe -raw 3 ..\video.mp4`

But when I try to import them again with this command
`mp4box.exe -add ..\GoproVideo.mp4 -set-meta meta:tk=3 -add-item ..\video_track3.gpmd:tk=3 -new output.mp4`

I got the following error
`Trying to add item, but missing meta box`

Am I missing something? Looking at the documentation, command line seems ok because I set the meta type and then add the item to it. Should I create first the track3? Or is automatically created with the set-meta command?

This is what I get if I run a -info on the original file
```
# Track 3 Info - ID 3 - TimeScale 1000
Media Duration 00:14:41.526
Track has 2 edits: track duration is 00:14:41.628
Track flags: Enabled In Movie In Preview
Media Samples: 8801
1 UDTA types:
        meta:
Media Type: meta:gpmd
        Unknown Metadata Stream
        RFC6381 Codec Parameters: gpmd
        All samples are sync
        Max sample duration: 104 / 1000
```

Thanks for reporting your issue. Please make sure these boxes are checked before submitting your issue - thank you!

- [x] I looked for a similar issue and couldn't find any.
- [x] I tried with the latest version of GPAC. Installers available at https://gpac.io/downloads/gpac-nightly-builds/
- [x] I give enough information for contributors to reproduce my issue (meaningful title, github labels, platform and compiler, command-line ...). I can share files anonymously with this dropbox: https://www.mediafire.com/filedrop/filedrop_hosted.php?drop=eec9e058a9486fe4e99c33021481d9e1826ca9dbc242a6cfaab0fe95da5e5d95

Detailed guidelines: https://gpac.io/bug-reporting/

**Comment by jeanlf** [comment]
I looks like trackID 3 is no longer present after import (I added a more explicit check in mp4box for that).

Can you run a -info on the output file without the -set-meta and -add-item options ?

**Comment by gabriele-v** [comment]
Hi @jeanlf sorry for the dealy.
I confirm that I don't have any trackID 3 in the output file, I was thinking i''s created by `-set-meta meta:tk=3`
Is there a way to create it and then import back my file as raw track?
I'm looking at gpac.exe filters as well but I'm not able to make it working.

Thanks!

**Comment by rbouqueau** [comment]
Sorry for being so late on this. Is the issue still relevant, and do we have a sample to reproduce?

**Comment by gabriele-v** [comment]
Hello, yes I've moved for a while to another project but this evening I'll test latest version and give you information to reproduce it. Thanks

**Comment by gabriele-v** [comment]
Hi @rbouqueau in order to reproduce the issue, you need to:
 
- Extract tmcd from original GoPro MP4 `mp4box.exe -raw 3 "SampleGopro10.mp4"`
- Extract gpmd from original GoPro MP4 `mp4box.exe -raw 4 "SampleGopro10.mp4"`

Then take another MP4 file, whatever you want with only video and audio track (so 2 tracks overall).
I need to add tmcd and gpmd into that new file, how can I do it?

I've tried with `mp4box.exe -add OnlyAudioVideo.mp4 -set-meta meta:tk=3 -add-item SampleGopro10_track3.tmcd -new output.mp4` but it has the error `No such track ID 3 in destination file`
Shouldn't `-set-meta meta:tk=3` create the track in destination file?

I've tried with `mp4box.exe -add OnlyAudioVideo.mp4 -add SampleGopro10_track3.tmcd -new output.mp4` but I have this error:
`IsoMedia import OnlyAudioVideo.mp4 - track ID 1 - Video (size 1920 x 1078)
IsoMedia import OnlyAudioVideo.mp4 - track ID 2 - Audio (SR 48000 - 2 channels)
[FFDmx] Fail to open ..\SampleGopro10_track3.tmcd - error Invalid data found when processing input
Filter ffdmx failed to setup: Filter not found for the desired type
Filters not connected:
mp4mx (importer:file=000002AB27E159D0) (idx=1)
[Importer] Error importing ..\SampleGopro10_track3.tmcd
Failure while importing media: Filter not found for the desired type
Error importing ..\SampleGopro10_track3.tmcd: Filter not found for the desired type`

Here you are the original GoPro MP4 file with additional tracks: https://www.mediafire.com/file/6pip6xe3dh4s26l/SampleGopro10.mp4/file


Thanks!

**Comment by gabriele-v** [comment]
Hi @jeanlf I've tried with latest head but I think it's not solved, now I have the error
```
No such track ID 3 in destination file
        Error: Bad Parameter
```

**Comment by jeanlf** [comment]
I fail to see what you are trying to achieve here:
- if you use -set-meta on a track, the track MUST be present. If you import an AV only file (likely track IDs 1 and 2), then there is no track ID=3
- if what you need is only to reimport the other tracks,  then simply do `MP4Box -add av.mp4 -add src_gopro.mp4#3 -add src_gopro.mp4#4 -new remux.mp4` - you may need to inject some track references back 

I added a more detailed error log, but the `-set-meta` behaves as expected in your command, so I'm closing this.

**Comment by jeanlf** [comment]
> GPMD file is a raw file with gopro data, not a real video track

It is timed metadata and is exposed as a track in mp4 (not all tracks are audio or video).

Since we don't natively support GPMD, we can export to raw (concatenation of GPMD samples) but we cannot re-import the file. The best way is to keep the GPMD data in a mp4 file (you can make a single-track MP4 with only GPMD data using e.g. `MP4Box -add GoPro.mp4#4 -new GPMD.mp4`) for later re-import.
